update script

diff --git a/.github/workflows/aws.dev.yml b/.github/workflows/aws.dev.yml
--- a/.github/workflows/aws.dev.yml
+++ b/.github/workflows/aws.dev.yml
@@ -72,7 +72,12 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no \
           ${{ secrets.PROD_EC2_USER }}@${{ secrets.AWS_DEV_DNS }} \
-          "python3 /home/ubuntu/scripts/updateServer.py --server test_server --dns 127.0.0.1"
+          "python3 /home/ubuntu/scripts/updateServer.py --server test_server --dns 127.0.0.1
+          if [ -f /home/ubuntu/nginx_updated.conf ]; then \
+            mv -f /home/ubuntu/nginx_updated.conf /home/ubuntu/liao_pastel-upstream-serv.conf; \
+          else \
+            echo '❌ Error: nginx_updated.conf 未生成'; exit 1; \
+          fi"
 
 
     
